train-subset: train_st
valid-subset: dev_st

max-epoch: 50
max-update: 500000

num-workers: 1
patience: 14
no-progress-bar: True
log-interval: 100
seed: 1
report-accuracy: True


arch: s2t_w2v2_mabrt_sead_s
adapter-model-path: # path to pretrained acoustic model （step 2）
decoder-embed-path: #path to the pretrained embedding (step 1)
load-pretrain-decoder: #path to mt decoder model (step 1)

share-decoder-input-output-embed: True
optimizer: adam
clip-norm: 10.0
lr-scheduler: inverse_sqrt
warmup-init-lr: 1e-7
warmup-updates: 8000
lr: 2e-4
adam-betas: (0.9,0.98)
adapter-dim: 4096
adapter-dropout: 0.0

criterion: label_smoothed_cross_entropy
label-smoothing: 0.2

use-cnn-module: False
cnn-module-kernel: 31

conv-kernel-sizes: 5,5
conv-channels: 1024
dropout: 0.1
activation-fn: relu
encoder-embed-dim: 1024
encoder-ffn-embed-dim: 4096
encoder-layers: 12
decoder-layers: 12
encoder-attention-heads: 16

decoder-embed-dim: 1024
decoder-ffn-embed-dim: 4096
decoder-attention-heads: 16
attention-dropout: 0.1
activation-dropout: 0.1
